version: '3.8'
services:
  mongo: 
    image: mongo:7.0.3
    ports:
      - '27017:27017'
    container_name: mongo_bd
      
  mongo_seed:
    build: ./Mongo Seed
    links:
      - mongo

  backend:
    build: ./Backend
    ports:
    - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    container_name: fast_api

  frontend:
    build: ./Frontend
    ports:
    - "5173:5173"
    links:
      - backend
    container_name: react_app